<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="2" total="3" passed="0">
  <reporter-output>
    <line>
      <![CDATA[HRM Login Method Started Execution]]>
    </line>
    <line>
      <![CDATA[HRM Login Method Started Execution]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="16138" started-at="2022-03-03T17:45:54Z" finished-at="2022-03-03T17:46:10Z">
    <groups>
      <group name="smoke">
        <method signature="TC002.verifyHRMAddEmp()[pri:0, instance:testscripts.TC002@76329302]" name="verifyHRMAddEmp" class="testscripts.TC002"/>
      </group> <!-- smoke -->
      <group name="sanity">
        <method signature="TC002.verifyHRMLogin()[pri:0, instance:testscripts.TC002@76329302]" name="verifyHRMLogin" class="testscripts.TC002"/>
        <method signature="TC001.verifyLogin()[pri:0, instance:testscripts.TC001@290dbf45]" name="verifyLogin" class="testscripts.TC001"/>
      </group> <!-- sanity -->
    </groups>
    <test name="Test" duration-ms="16138" started-at="2022-03-03T17:45:54Z" finished-at="2022-03-03T17:46:10Z">
      <class name="testscripts.TC001">
        <test-method status="PASS" signature="setup()[pri:0, instance:testscripts.TC001@290dbf45]" name="setup" is-config="true" duration-ms="6865" started-at="2022-03-03T23:15:54Z" finished-at="2022-03-03T23:16:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="verifyLogin()[pri:0, instance:testscripts.TC001@290dbf45]" name="verifyLogin" duration-ms="1879" started-at="2022-03-03T23:16:01Z" finished-at="2022-03-03T23:16:03Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[actual URL does not match with Expected URL expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: actual URL does not match with Expected URL expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:288)
	at utilities.Browser.verifyURL(Browser.java:31)
	at pages.HRMLogin.hrmLogin(HRMLogin.java:46)
	at testscripts.TC001.verifyLogin(TC001.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.TestNG.privateMain(TestNG.java:1325)
	at org.testng.TestNG.main(TestNG.java:1294)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[HRM Login Method Started Execution]]>
            </line>
          </reporter-output>
        </test-method> <!-- verifyLogin -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:testscripts.TC001@290dbf45]" name="teardown" is-config="true" duration-ms="48" started-at="2022-03-03T23:16:03Z" finished-at="2022-03-03T23:16:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testscripts.TC001 -->
      <class name="testscripts.TC002">
        <test-method status="PASS" signature="setup()[pri:0, instance:testscripts.TC002@76329302]" name="setup" is-config="true" duration-ms="5912" started-at="2022-03-03T23:16:03Z" finished-at="2022-03-03T23:16:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="verifyHRMLogin()[pri:0, instance:testscripts.TC002@76329302]" name="verifyHRMLogin" duration-ms="1379" started-at="2022-03-03T23:16:09Z" finished-at="2022-03-03T23:16:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[actual URL does not match with Expected URL expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: actual URL does not match with Expected URL expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:288)
	at utilities.Browser.verifyURL(Browser.java:31)
	at pages.HRMLogin.hrmLogin(HRMLogin.java:46)
	at testscripts.TC002.verifyHRMLogin(TC002.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.TestNG.privateMain(TestNG.java:1325)
	at org.testng.TestNG.main(TestNG.java:1294)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[HRM Login Method Started Execution]]>
            </line>
          </reporter-output>
        </test-method> <!-- verifyHRMLogin -->
        <test-method status="SKIP" signature="verifyHRMAddEmp()[pri:0, instance:testscripts.TC002@76329302]" name="verifyHRMAddEmp" duration-ms="0" started-at="2022-03-03T23:16:10Z" depends-on-methods="testscripts.TC002.verifyHRMLogin" finished-at="2022-03-03T23:16:10Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC002.verifyHRMAddEmp()[pri:0, instance:testscripts.TC002@76329302] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC002.verifyHRMAddEmp()[pri:0, instance:testscripts.TC002@76329302] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1040)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.TestNG.privateMain(TestNG.java:1325)
	at org.testng.TestNG.main(TestNG.java:1294)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyHRMAddEmp -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:testscripts.TC002@76329302]" name="teardown" is-config="true" duration-ms="48" started-at="2022-03-03T23:16:10Z" finished-at="2022-03-03T23:16:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testscripts.TC002 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
